### ISSUE TITLE
NullInjectorError: No provider for TranslateService!

### ISSUE THREAD

**Issue by vochitan90** [SimonTestNet/ng-cache-testing-module#3]
Hi there, 

when I use this plugin -> Error occured

package.json
"test": "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng test --browsers=Chrome",

error: 
NullInjectorError: R3InjectorError(DynamicTestModule)[LoaderService -> TranslateService -> TranslateService]: 
      NullInjectorError: No provider for TranslateService!
    error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'LoaderService', 'TranslateService', 'TranslateService' ] })
    NullInjectorError: R3InjectorError(DynamicTestModule)[LoaderService -> TranslateService -> TranslateService]: 
      NullInjectorError: No provider for TranslateService!
        at NullInjector.get (node_modules/@angular/core/fesm2020/core.mjs:6359:27)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6786:33)
        at injectInjectorOnly (node_modules/@angular/core/fesm2020/core.mjs:4782:33)
        at Module.ɵɵinject (node_modules/@angular/core/fesm2020/core.mjs:4786:12)
        at Object.factory (node_modules/@mobiliar/mobi-core-lib/fesm2020/mobiliar-mobi-core-lib.mjs:3648:1)
        at R3Injector.hydrate (node_modules/@angular/core/fesm2020/core.mjs:6887:35)
        at R3Injector.get (node_modules/@angular/core/fesm2020/core.mjs:6775:33)
        at ChainedInjector.get (node_modules/@angular/core/fesm2020/core.mjs:13769:36)
        at lookupTokenUsingModuleInjector (node_modules/@angular/core/fesm2020/core.mjs:3293:39)

Using Angular 14 with jasmine test.

My TestBed config code:
```
TestBed.configureTestingModule({
            imports: [
                HttpClientModule,
                TranslateModule.forRoot({
                    loader: { provide: TranslateLoader, useClass: FakeLoaderMock }
                }),
            ],
            declarations: [SettingsComponent],
            providers: [TranslateService],
            schemas: [NO_ERRORS_SCHEMA]
        });
```

**Comment by Etiake** [comment]
Hi! I have the same issue after upgrading to Angular 14. Is there a workaround?
